#!/bin/zsh

# okay so I've been at this for a while and reviewing the ports list option makes this script almost impossible, the logic hurts my brain and it will take MANY cases or if statements to continue the port selection portion of this script AND this doesn't include -sC, -sV, -sS, -v, -T<X> AND MORE.
# instead I am focusing on a preset nmap script instead, which will make my job significantly more easier
# === idea: presets ===
# user input: targetIP
# port specific with and without timing, with and without scan tacs nmap options
# host discovery with and without options /24 included at end of query
# basic scan without any tacs at all

x=1

while [ $x -eq 1 ];
  do
    echo "Input targetIP (X.X.X.X): "
    read targetIP
    echo "targetIP $targetIP [Y/n]"
    read targetIPresp
    if [[ $targetIPresp != [Yy] ]]
      then
      break
    else
      echo "Would you like to add more parameters? [Y/n]"
      read parameterResp
    fi
    if [[ $parameterResp != [Yy] ]]
      then
      echo $x
      nmap $targetIP
      break
    else
      echo "Would you like to add port/s? [Y/n]"
      read portResp
    fi
    if [[ $portResp != [Yy] ]]
      then
      nmap $targetIP
      # add prompt for other items as well
      break
    else
      echo "Top 1000, all port scan or specific ports? [1/2/3] "
      read portSpecific
    fi
    if [[ $portSpecific = 1 ]]
      then
      echo "Top 1000 selected"
      nmap $targetIP
      break
    elif [[ $portSpecific = 2 ]]
    then
      echo "-p-"
      nmap -p- $targetIP
      break
    elif [[ $portSpecific = 3 ]]
    then
      echo "Which port/s?\n1.20\n2.22\n3.22\n4.23\m5.24\n6.25\n7.53\m8.80\n9.88\n10.110\n11.443\n12.445\n13.3306\n14.3389\n"
      read -r portInput portInputTwo
      echo $portInput $portInputTwo
      portInput="-p$portInput $portInputTwo "
      echo $targetIP $portInput $portInputTwo
      nmap $portInput $portInputTwo $targetIP
      echo $x
      break
    else
      echo "Jumped to last"
      echo "Please input a valid response! "
    fi
  done

===========================

#!/bin/zsh

echo "Input targetIP: X.X.X.X "
read targetIP
echo "targetIP $targetIP [Y/n]"
read targetIPresp
if [[ $targetIPresp != [Yy] ]]
then exit 1
else
echo "Would you like to add more parameters? [Y/n]"
read parameterResp
fi
if [[ $parameterResp != [Yy] ]]
then nmap $targetIP
else
echo "Would you like to add port/s? [Y/n]"
read portResp
fi
if [[ $portResp != [Yy] ]]
then
else
echo "Top 1000, all port scan or specific ports? [1/2/3] "
read portSpecific
fi
if [[ $portSpecific = 1 ]]
then
echo "Top 1000 selected"
nmap -p $targetIP
elif [[ $portSpecific = 2 ]]
then
echo "-p-"
nmap -p- $targetIP
elif [[ $portSpecific = 3 ]]
then
echo "Which port/s? (22,80) "
read -r portInput portInputTwo
echo $portInput $portInputTwo
portInput="-p$portInput $portInputTwo"
echo $targetIP $portInput $portInputTwo
nmap $portInput $portInputTwo $targetIP
else
echo "Please input a valid response! "
fi

Adding more functionality

=== ideas ===
echo “Input targetIP: 10.0.0.138”
read targetIP
echo “Is this correct? $targetIP [Y/n]”
read targetIPresp
If [[ $targetIPresp -ne [Yy] ]]
then
exit 1
else
echo “Would you like to add more parameters? [Y/N]”
read parameterResp
if [[ $parameterResp -ne [Yy] ]]
then
nmap $targetIP
else
echo “Would you like to add port/s? “
read portResp
if [[ $portResp -ne [Yy] ]]
then
else
echo “Top 1000, All Port scan or specific ports? [1/2/3]”
read portSpecific
if [[ $portSpecific -eq 1 ]]

elif [[ $portSpecific -eq 2 ]]

elif [[ $portSpecific -eq 3 ]]

else
echo “Please input valid response!\n”
return 1

echo “Input ports: [XX/XXX/XXX] ”


nmap $port $stealthScan $defaultScripts $versioning $operatingSystems $timing $verbosity $targetIP

Nmap -p80,443,3306,445,3389 -sS -sC -sV -O -T4 -v 10.0.0.138

